// <auto-generated />
using System;
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20200821204529_RemoveEnums")]
    partial class RemoveEnums
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("AdoptionDate");

                    b.Property<int>("Age");

                    b.Property<string>("Breed");

                    b.Property<DateTime>("CheckInDate");

                    b.Property<string>("Gender");

                    b.Property<bool>("IsAdopted");

                    b.Property<string>("Name");

                    b.Property<string>("Species");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 7,
                            Breed = "Tabby",
                            CheckInDate = new DateTime(2017, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            IsAdopted = false,
                            Name = "Boots",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 4,
                            Breed = "Retriever",
                            CheckInDate = new DateTime(2019, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            IsAdopted = false,
                            Name = "Bandit",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 3,
                            Breed = "Siamese",
                            CheckInDate = new DateTime(2017, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            IsAdopted = false,
                            Name = "Felix",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 2,
                            Breed = "Collie",
                            CheckInDate = new DateTime(2019, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            IsAdopted = false,
                            Name = "Lassie",
                            Species = "Dog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
